title: FedLab
email: dirg@umu.se
description: >
  A test suite for identity federation protocols, OAuth, OpenID Connect and SAML
baseurl: "/Users/rhoerbe/devl/wwwFed-labOrg/_site/" # the subpath of your site, e.g. /blog
url: "fed-lab.org" # the base hostname & protocol for your site

# Footer Settings
credit: Theme by <a href="https://themehall.com/">ThemeHall</a>

exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      use_jumbotron: "yes"
      show_on_menu: "yes"
